package AutomationSyntax;
/*Alert is not an HTML element within a DOM. it is an written inside a script which is a
 * funtion of JavaScript. Hence it cannot be located by using xpath. 
 * When Alert pops up it does not allow you to do anything else. It has to be handled first.
 * It is generated by clicking some button where click me is written. There are thre types
 * accept, dismiss and entertext+ok. 
 * The function of the alert box is to seek confirmation from the user about the action being 
 * performed
 */
public class HowToHandleAlert {
	//driver.findElement(By.xpath("")).click(); (this will generate the page after clicking
	//on this an alert will be generated
	//driver.switchTo().alert();
	//alert.accept();
	//alert.dismiss();
	//alert.sendKeys("Govind");
	//alert.click();
	
	

}
